[build]
  command = "pnpm build"
  publish = "dist"

# SPA fallback so React Router works on refresh and deep links
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: caching headers (safe defaults)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
