// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bychsufmyenzfuruujys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5Y2hzdWZteWVuemZ1cnV1anlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2OTQxMzIsImV4cCI6MjA3NjI3MDEzMn0.lBng1KJxyGlZiahv1NHg_u7IWj8quEoldDe0zkrNT1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});